<?php
/**
 * @file sivumestari_wysiwyg_2.module
 */

/**
 * Implements of hook_element_info_alter().
 */
function sivumestari_wysiwyg_element_info_alter(&$type) {
    // Change text format processing on elements to our version.
    // Vaihtaa elementtien tekstin muodon omaan käyttöön sopivaksi.
    if (isset($type['text_format'])) {
        $type['text_format']['#process'][] = 'sivumestari_wysiwyg_filter_process_format';
    }
}

/**
 * Callback for processing the text_format element
 */
function sivumestari_wysiwyg_filter_process_format($element) {

    // Set the element above the WYSIWYG textarea
    // Asettaa elementin WYSIWYG alueen yläpuolelle
    $element['format']['#weight'] = 1;
    $element['format']['#prefix'] = '<div class="format-toggle">';
    $element['format']['#suffix'] = '</div><div class="clearfix"></div>';
    unset($element['format']['#type']);
    $element['format']['format']['#title'] = 'Editor: ';

    // Do not show the guidelines and help text for text formatters
    // Älä näytä ohjeita ja apu-tekstejä tekstinkäsittelijöille
    if (!variable_get('sivumestari_wysiwyg_show_format_details', FALSE)) {
        $element['format']['help']['#access'] = FALSE;
        $element['format']['guidelines']['#access'] = FALSE;
    }

    return $element;
}