<?php

include_once('sivumestari_pages.features.inc');

/**
 * Implementation of drupal_alter() to update menu block settings in 
 * case of IPE callback magic. This will only work in limited cases
 * but will be fixed when the page refreshes. 
 */
function sivumestari_pages_menu_block_tree_alter($tree, $config) {
  if (arg(0) == 'panels' && arg(1) == 'ajax') {
    foreach ($tree as $key => $value) {
      $tree[$key]['link']['in_active_trail'] = TRUE;
    }
  }
}

/**
 * Implementation of hook_menu
 */
function sivumestari_pages_menu() {
  $items['node/add/landing_page'] = array(
    'title' => 'Landing Page',
    'description' => t('A primary landing page to display to users on your site.'),
    'page callback' => 'page_manager_page_wizard',
    'page arguments' => array(2),
    'access arguments' => array('use page manager'),
    'file' => 'includes/page-wizard.inc',
    'file path' => drupal_get_path('module', 'ctools'),
  );
  return $items;
}

/**
 * Implementation of hook_form_alter()
 */
function sivumestari_pages_form_alter(&$form, &$form_state, $form_id) {

}


/**
 * Implementation of hook_module_implements_alter()
 */
function sivumestari_pages_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'form_alter') {
    $group = $implementations['sivumestari_pages'];
    unset($implementations['sivumestari_pages']);
    $implementations['sivumestari_pages'] = $group;
  }
}

